# .readthedocs.yaml -*- mode: YAML -*-
# https://blog.readthedocs.com/migrate-configuration-v2/
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: jgdv/_docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv
    create_environment:
      - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --group docs 
    build:
      html:
        - echo "Building HTML"
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - >
          UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}"
          OUTDIR="${READTHEDOCS_OUTPUT}/html/"
          DOCTREE="_build/doctrees"
          uv run tox -e docs
