# -*- mode:conf-toml; -*-

[startup]

loaders                  = { commands="default", task="default", parser="default"}
location_check           = { make_missing = true, print_levels={action="WARN", execute="WARN"}}
sources = {tasks=[".tasks", "~/.config/.templates/doot/repo_chores"], code=[]}
sleep   = { tasks=0.2, subtask=1, batch=1 }

[startup.plugins]
# Allows for defining aliases
command        = { tasks="doot.cmds.list_cmd:ListCmd", pl="doot.cmds.plugins_cmd:PluginsCmd" }

[startup.commands]
# Settings for commands, like telling the 'run' command what backends to use
run  = { tracker = "default", runner = "default", reporter= "default", report-line = []}
list = { hide=[] }

[logging]
# Standard loggers. See LoggerSpec.
stream  = { level="WARNING", filter=["doot"],           target="stdout", format="{levelname:<8} : {message}"  }
file    = { level="DEBUG",   filter=["chainguard"],      target="rotate", format="{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filename_fmt="doot.log" }
printer = { level="NOTSET", colour=true,                target=["stdout", "rotate"], format="{message}", filename_fmt="doot_printed.log" }

[logging.subprinters]
default       = {level="WARNING"}
shutdown      = {level="WARNING",    format="Shutdown: {message}", target="stdout"}
cmd           = {level="INFO"}
task          = {level="INFO" }
header        = {level="INFO" }
task_header   = {level="INFO"}

[[locations]]
tasks        = {loc=".tasks", protected=true}
temp         = {loc=".temp",  cleanable=true}
src          = {loc="jgdv",   protected=true}
logs         = "{temp}/logs"
build        = "{temp}/build"
