# towncrier.toml -*- mode: toml-mode -*-
# Summary:
#
# Tags:
#
## https://towncrier.readthedocs.io/en/stable/configuration.html
[tool.towncrier]
name                  = "jgdv"
version               = "1.3.3"
directory             = "jgdv/_docs/_changes"
filename              = "CHANGELOG.md"
template              = "jgdv/_docs/_templates/news.md"
create_add_extension  = true

