
class BaseClass: ...
class Mixin1: ...
class Mixin2: ...


# Instead of this:
class MyClass(Mixin1, Mixin2, BaseClass): ...

# This:
from jgdv.decorators import Mixin


@Mixin(Mixin1, Mixin2)
class MyClass2(BaseClass): ...
